Repository alfaPegasis/dsa-all, pull requests merged in 2022-10, with the labels that each got.

#5 create dfs.py
  Algorithms/Python/dfs.py
Labels: hacktoberfest-accepted

#7 Revert "Create heapSort.py"
  Algorithms/Python/heapSort.py
Labels: hacktoberfest-accepted

#6 create bfs.py
  Algorithms/Python/bfs.py
Labels: hacktoberfest-accepted

#8 create linked_list.py
  Data Structures/Python/linked_list.py
Labels: hacktoberfest-accepted

#9 create binary_tree.py
  Data Structures/Python/binary_tree.py
Labels: hacktoberfest-accepted

#12 insertion sort using javascrpt
  Algorithms/JavaScript/BubbleSort.js
  Algorithms/JavaScript/InsertionSort.js
Labels: hacktoberfest-accepted

#13 merge sort using JavaScript
  Algorithms/JavaScript/MergeSort.js
Labels: hacktoberfest-accepted

#14 reverse linked list
  Data Structures/JavaScript/ReverseLinkedList.js
Labels: hacktoberfest-accepted

#15 decimal to binary conversion using stack
  Data Structures/JavaScript/DecimalToBinaryUsingStack.js
Labels: hacktoberfest-accepted

#18 Prim's Algorithm using JavaScript
  Algorithms/Prims.js
Labels: hacktoberfest-accepted

#17 add linear search in java
  Algorithms/Java/linearsearch.java
Labels: hacktoberfest-accepted

#19 Kruskal's algorithm using javascript
  Algorithms/JavaScript/Kruskal.js
Labels: hacktoberfest-rejected

#20 add binary search in java
  Algorithms/Java/binarysearch.java
Labels: hacktoberfest-accepted

#28 Stack in java
  Data Structures/Java/Stack.java
Labels: hacktoberfest-accepted

#27 add linked list
  Data Structures/C++/linkedList.cpp
  Data Structures/C++/stack.cpp
Labels: hacktoberfest-accepted

#30 add: LinkedList JavaScript
  Data Structures/JavaScript/LinkedList.js
Labels: hacktoberfest-accepted

#29 Queue implementation using javascript
  Algorithms/JavaScript/Queue.js
Labels: hacktoberfest-accepted

#31 Feat heap
  Algorithms/JavaScript/Prims.js
  Algorithms/Python/heap.py
Labels: hacktoberfest-accepted

#32 Queue implementation using javascript
  Data Structures/JavaScript/Queue.js
Labels: hacktoberfest-accepted

#33 Quicksort using javascript
  Algorithms/JavaScript/QuickSort.js
Labels: enhancement, hacktoberfest-accepted

#35 floodfill using javascript
  Algorithms/JavaScript/FloodFill.js
Labels: hacktoberfest-accepted

#37 feat binary search in js
  Algorithms/JavaScript/binarySearch.js
Labels: hacktoberfest-accepted

#36 feat selection sort in js
  Algorithms/JavaScript/selectionSort.js
Labels: hacktoberfest-accepted

#41 add merge sort.cpp
  Algorithms/C++/mergeSort.cpp
Labels: hacktoberfest-accepted

#42 fib search algorithm
  Data Structures/JavaScript/fib_search.js
Labels: hacktoberfest-accepted

#43 selection sort in cpp
  Algorithms/C++/selectionSort.cpp
Labels: hacktoberfest-accepted

#44 Add Tim sort python
  Algorithms/Python/timSort.py
Labels: hacktoberfest-accepted

#46 array in java
  Data Structures/Java/array.java
Labels: hacktoberfest-accepted

#45 added stack using templates program in cpp
  Data Structures/C++/stack_usingTemplates.cpp
Labels: hacktoberfest-accepted

#38 Created Linked List
  Data Structures/Java/LinkedList.java
Labels: hacktoberfest-accepted

#47 graph algorithm
  Algorithms/Python/shortestPathGraph.py
Labels: hacktoberfest-accepted

#48 Adding DFS and BFS
  Algorithms/Java/BreadthFirstSearch.java
  Algorithms/Java/DepthFirstSearch.java
Labels: hacktoberfest-accepted

#49 Create doubly linked list.cpp
  Data Structures/C++/doubly linked list.cpp
Labels: hacktoberfest-accepted

#51 Adding hashtable implementation
  Data Structures/Java/HashTable.java
  Data Structures/Java/UpdatedHashTable
Labels: hacktoberfest-accepted

#50 Uploaded Heap Sort
  Algorithms/C++/heapSort.cpp
Labels: hacktoberfest-accepted

#55 Breadth first search using JavaScript
  Data Structures/JavaScript/BFS.js
Labels: hacktoberfest-accepted

#53 HashSet using Javascript
  Data Structures/JavaScript/HashSets.js
Labels: hacktoberfest-accepted

#52 Set and Set functions in Javacript
  Data Structures/JavaScript/Sets.js
Labels: hacktoberfest-accepted

#57 SortLinkedList.java
  Algorithms/Java/SortLinkedList.java
Labels: hacktoberfest-accepted

#60 Create Queue.java
  DataStructures/Java/Queue.java
Labels: hacktoberfest-accepted

#61 Create BubbleSort.java
  Algorithms/Java/BubbleSort.java
Labels: hacktoberfest-accepted

#59 Create DoublyLinkedList.java
  DataStructures/Java/DoublyLinkedList.java
Labels: hacktoberfest-accepted

#62 add circularLinkedList.cpp
  Data Structures/C++/circularLinkedList.cpp
  Data Structures/C++/doublyLinkedList.cpp
Labels: hacktoberfest-accepted

#64 Mergesort and quick sort in java
  MergeSort.java
  QuickSort.java
Labels: hacktoberfest-accepted

#69 add fibonacciHeap.cpp
  Data Structures/C++/fibonacciHeap.cpp
Labels: hacktoberfest-accepted

#70 add treeTraversal.cpp
  Data Structures/C++/treeTraversal.cpp
Labels: hacktoberfest-accepted

#73 Shell Sort in JAVA
  Algorithms/Java/Shellsort.java
Labels: hacktoberfest-accepted

#75 Create Floyd_Algorithm.cpp
  Algorithms/C++/Floyd_Algorithm.cpp
Labels: hacktoberfest-accepted

#77 merge_sort for Python
  Algorithms/Python/merge_sort
Labels: hacktoberfest-accepted

#78 add bubble sort
  Algorithms/Python/bubbleSort.py
  Algorithms/Python/mergeSort.py
Labels: hacktoberfest-accepted

#79 Python Program for Dijkstra’s shortest path algorithm
  Algorithms/JavaScript/timSort.js
  Algorithms/Python/dijkstra.py
Labels: hacktoberfest-accepted

#80 Create timSort.java
  Algorithms/Java/timSort.java
Labels: hacktoberfest-accepted

#81 Create avl.cpp
  Algorithms/C++/avl.cpp
Labels: hacktoberfest-accepted

#82 Create tree.cpp
  Data Structures/C++/tree.cpp
Labels: hacktoberfest-accepted

#83 Create avl.js
  Data Structures/JavaScript/avl.js
Labels: hacktoberfest-accepted

#85 Feat: AVL algorithm in js cpp and python
  Algorithms/JavaScript/avl.js
  Algorithms/Python/avl.py
Labels: hacktoberfest-accepted

#84 Create insertion_sort.cpp
  Algorithms/C++/insertion_sort.cpp
Labels: hacktoberfest-accepted

#89 Binary search tree using Javascript
  Data Structures/JavaScript/BinarySearchTree.js
Labels: hacktoberfest-accepted

#86 DFS using JavaScript
  Data Structures/JavaScript/DFS.js
Labels: hacktoberfest-accepted

#88 Prority Queue implmentation using javascript
  Data Structures/JavaScript/PriorityQueue.js
Labels: hacktoberfest-accepted

#92 folder restructure
  Data Structures/Java/DoublyLinkedList.java
  Data Structures/Java/Queue.java
Labels: hacktoberfest-accepted

#91 Create Quick sort.cpp
  Algorithms/C++/Quick sort.cpp
Labels: hacktoberfest-accepted

#90 Create Cyclic sort.cpp
  Algorithms/C++/Cyclic sort.cpp
Labels: hacktoberfest-accepted

#93 add bitonicSort.cpp
  Algorithms/C++/bitonicSort.cpp
Labels: hacktoberfest-accepted

#96 add pigeonholeSort.cpp
  Algorithms/C++/pigeonholeSort.cpp
Labels: hacktoberfest-accepted

#95 Add BFS algorithm in JavaScript
  Algorithms/JavaScript/bfs.js
Labels: hacktoberfest-accepted

#97 Add heap sort in JavaScript
  Algorithms/JavaScript/heapSort.js
Labels: hacktoberfest-accepted

#98 Add radix sort in JavaScript
  Algorithms/JavaScript/radixSort.js
Labels: hacktoberfest-accepted

#99 Add shell sort in Javascript
  Algorithms/JavaScript/shellSort.js
Labels: hacktoberfest-accepted

#100 Add counting sort in Javascript
  Algorithms/JavaScript/countingSort.js
Labels: hacktoberfest-accepted

#101 added sieveOfEratosthenes.py
  Algorithms/Python/sieveOfErtosthenes.py
Labels: hacktoberfest-accepted

#102 Transpose of graph.cpp
  Data Structures/C++/Graph.cpp
  Data Structures/C++/Transpose of graph.cpp
Labels: hacktoberfest-accepted

#103 Create LinkedList.py
  Data Structures/Python/LinkedList.py
Labels: hacktoberfest-accepted

#105 Create Queue.py
  Data Structures/Python/Queue.py
Labels: hacktoberfest-accepted

#104 Create Stack.py
  Data Structures/Python/Stack.py
Labels: hacktoberfest-accepted

#106 Create Graph.py
  Data Structures/Python/Graph.py
Labels: hacktoberfest-accepted

#111 Pegionhole sort using javascript
  Algorithms/JavaScript/PigeonHole.js
Labels: hacktoberfest-accepted

#110 Kniight tour using javascript
  Algorithms/JavaScript/TheKnightTour.js
Labels: hacktoberfest-accepted

#109 Hamiltonian path using javascript
  Algorithms/JavaScript/HamiltonianPath.js
Labels: hacktoberfest-accepted

#108 Subset sum using Javascript
  Algorithms/JavaScript/SubsetSum.js
Labels: hacktoberfest-accepted

#107 added subset sum in javascript
  Algorithms/JavaScript/subsetSum.js
Labels: hacktoberfest-accepted

#112 add pascalTriangle
  Algorithms/JavaScript/pascalTriangle.js
Labels: hacktoberfest-accepted

#113 add primaryFactors.js
  Algorithms/JavaScript/primaFactors.js
Labels: hacktoberfest-accepted

#114 add Liu Hui's π algorithm
  Algorithms/JavaScript/liuHui.js
Labels: hacktoberfest-accepted
